In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [76]:
# Read the dataset
df = pd.read_csv('/content/drive/My Drive/aiml/Residency7_AI/NNDL_Proj1/bank.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [77]:
# Drop the columns that are not required i.e., that do not contribute to prediction like Rownumber, CustomerID and Surname
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
#Distinguish the feature and target set
X = df.iloc[:,0:10] # CreditScore to EstimatedSalary
y = df.iloc[:, 10] # Exited

In [79]:
X.head()

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [0]:
# Encoding categorical data (Geography Column)

le1 = LabelEncoder()
X.iloc[:,1] = le1.fit_transform(X.iloc[:,1])

In [81]:
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [82]:
#Apply Label Encoding on Gender Column
le2 = LabelEncoder()
X.iloc[:, 2] = le2.fit_transform(X.iloc[:, 2])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [83]:
# Apply OneHotEncoding to Geography column so that model does not treat the Geography as Ordinal values
# One-hot encode categorical features and drop first value column
#no need to encode Gender, as there are only two categories

encoded = pd.DataFrame(to_categorical(X.iloc[:, 1]))

X = pd.concat([encoded, X], axis = 1)
X.head()

     0    1    2  ...  HasCrCard  IsActiveMember  EstimatedSalary
0  1.0  0.0  0.0  ...          1               1        101348.88
1  0.0  0.0  1.0  ...          0               1        112542.58
2  1.0  0.0  0.0  ...          1               0        113931.57
3  1.0  0.0  0.0  ...          0               0         93826.63
4  0.0  0.0  1.0  ...          1               1         79084.10

[5 rows x 13 columns]

In [84]:
#Dropping the existing "Geography" column, and one of the onehotcoded columns.

X = X.drop([0,'Geography'], axis = 1)
X.head()

     1    2  CreditScore  ...  HasCrCard  IsActiveMember  EstimatedSalary
0  0.0  0.0          619  ...          1               1        101348.88
1  0.0  1.0          608  ...          0               1        112542.58
2  0.0  0.0          502  ...          1               0        113931.57
3  0.0  0.0          699  ...          0               0         93826.63
4  0.0  1.0          850  ...          1               1         79084.10

[5 rows x 11 columns]

In [0]:
#Divide the data set into Train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 7)

In [0]:
# Apply Standard Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
# Build NNDL Model

#Initialize Model
model = Sequential()
#Input Layer
model.add(Dense(activation = 'relu', input_dim = 11, units=6, kernel_initializer='uniform'))
#Hidden Layer
model.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 
# Output Layer
model.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform'))

In [0]:
# Compile the Model
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [89]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_4 (Dense)              (None, 6)                 72
_________________________________________________________________
dense_5 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

In [90]:
# Model fitting
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
7000/7000 [==============================] - 1s 146us/step - loss: 0.4945 - acc: 0.7954
Epoch 2/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4305 - acc: 0.7954
Epoch 3/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4247 - acc: 0.7954
Epoch 4/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4201 - acc: 0.8119
Epoch 5/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4175 - acc: 0.8254
Epoch 6/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4152 - acc: 0.8281
Epoch 7/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4134 - acc: 0.8311
Epoch 8/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.4117 - acc: 0.8320
Epoch 9/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4109 - acc: 0.8336
Epoch 10/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4098 - acc: 0.8326
Epoch 11/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.4084 - acc: 0.8344
Epoch 12/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4075 - acc: 0.8334
Epoch 13/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4067 - acc: 0.8363
Epoch 14/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4063 - acc: 0.8350
Epoch 15/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4058 - acc: 0.8363
Epoch 16/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4049 - acc: 0.8370
Epoch 17/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4044 - acc: 0.8346
Epoch 18/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4039 - acc: 0.8367
Epoch 19/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4040 - acc: 0.8366
Epoch 20/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4036 - acc: 0.8359
Epoch 21/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.4031 - acc: 0.8354
Epoch 22/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4030 - acc: 0.8373
Epoch 23/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4021 - acc: 0.8359
Epoch 24/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.4028 - acc: 0.8359
Epoch 25/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4026 - acc: 0.8364
Epoch 26/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4023 - acc: 0.8367
Epoch 27/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4018 - acc: 0.8360
Epoch 28/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4020 - acc: 0.8361
Epoch 29/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4016 - acc: 0.8367
Epoch 30/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4014 - acc: 0.8361
Epoch 31/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4011 - acc: 0.8357
Epoch 32/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4009 - acc: 0.8386
Epoch 33/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4006 - acc: 0.8353
Epoch 34/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4012 - acc: 0.8373
Epoch 35/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4012 - acc: 0.8359
Epoch 36/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4007 - acc: 0.8363
Epoch 37/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.4003 - acc: 0.8389
Epoch 38/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.4007 - acc: 0.8354
Epoch 39/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3998 - acc: 0.8349
Epoch 40/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.4000 - acc: 0.8374
Epoch 41/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4002 - acc: 0.8361
Epoch 42/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3999 - acc: 0.8374
Epoch 43/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4003 - acc: 0.8371
Epoch 44/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4003 - acc: 0.8366
Epoch 45/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3997 - acc: 0.8371
Epoch 46/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3997 - acc: 0.8377
Epoch 47/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3998 - acc: 0.8366
Epoch 48/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4000 - acc: 0.8363
Epoch 49/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3996 - acc: 0.8357
Epoch 50/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3996 - acc: 0.8393
Epoch 51/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3995 - acc: 0.8354
Epoch 52/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.3998 - acc: 0.8370
Epoch 53/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3993 - acc: 0.8377
Epoch 54/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3995 - acc: 0.8356
Epoch 55/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.3995 - acc: 0.8377
Epoch 56/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3998 - acc: 0.8360
Epoch 57/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3988 - acc: 0.8361
Epoch 58/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3993 - acc: 0.8366
Epoch 59/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3995 - acc: 0.8360
Epoch 60/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3992 - acc: 0.8381
Epoch 61/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3997 - acc: 0.8364
Epoch 62/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3988 - acc: 0.8373
Epoch 63/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3989 - acc: 0.8383
Epoch 64/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3991 - acc: 0.8360
Epoch 65/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3990 - acc: 0.8373
Epoch 66/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3987 - acc: 0.8373
Epoch 67/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3989 - acc: 0.8371
Epoch 68/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3986 - acc: 0.8356
Epoch 69/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3994 - acc: 0.8381
Epoch 70/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3991 - acc: 0.8350
Epoch 71/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3990 - acc: 0.8367
Epoch 72/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3990 - acc: 0.8360
Epoch 73/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3987 - acc: 0.8387
Epoch 74/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3985 - acc: 0.8369
Epoch 75/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3988 - acc: 0.8383
Epoch 76/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.3990 - acc: 0.8361
Epoch 77/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3991 - acc: 0.8364
Epoch 78/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3990 - acc: 0.8380
Epoch 79/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3989 - acc: 0.8367
Epoch 80/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3988 - acc: 0.8357
Epoch 81/100
7000/7000 [==============================] - 1s 106us/step - loss: 0.3987 - acc: 0.8357
Epoch 82/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3982 - acc: 0.8359
Epoch 83/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3987 - acc: 0.8389
Epoch 84/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.3983 - acc: 0.8381
Epoch 85/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3982 - acc: 0.8367
Epoch 86/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3985 - acc: 0.8376
Epoch 87/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3987 - acc: 0.8379
Epoch 88/100
7000/7000 [==============================] - 1s 122us/step - loss: 0.3984 - acc: 0.8363
Epoch 89/100
7000/7000 [==============================] - 1s 120us/step - loss: 0.3982 - acc: 0.8384
Epoch 90/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3986 - acc: 0.8364
Epoch 91/100
7000/7000 [==============================] - 1s 122us/step - loss: 0.3985 - acc: 0.8364
Epoch 92/100
7000/7000 [==============================] - 1s 121us/step - loss: 0.3974 - acc: 0.8381
Epoch 93/100
7000/7000 [==============================] - 1s 121us/step - loss: 0.3983 - acc: 0.8357
Epoch 94/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3980 - acc: 0.8383
Epoch 95/100
7000/7000 [==============================] - 1s 120us/step - loss: 0.3981 - acc: 0.8363
Epoch 96/100
7000/7000 [==============================] - 1s 125us/step - loss: 0.3984 - acc: 0.8369
Epoch 97/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3982 - acc: 0.8367
Epoch 98/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3977 - acc: 0.8351
Epoch 99/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.3983 - acc: 0.8366
Epoch 100/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3984 - acc: 0.8367

In [91]:
#Predict the results using 0.5 as a threshold 
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]

In [92]:
# Accuracy Score
print("Accuracy")
print(accuracy_score(y_test, y_pred))

Accuracy
0.8353333333333334

In [93]:
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

Confusion Matrix
[[2293  102]
 [ 392  213]]