## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.utils import np_utils
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

Using TensorFlow backend.

In [2]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default
#tf.enable_eager_execution()

### Collect Data

In [3]:
import pandas as pd

In [4]:
df= pd.read_csv('prices.csv')

### Check all columns in the dataset

In [5]:
df.shape

(851264, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB

### Drop columns `date` and  `symbol`

In [7]:
df = df.drop(['date','symbol'],axis=1)

In [8]:
df.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [9]:
df = df.iloc[0:1000, :]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
open      1000 non-null float64
close     1000 non-null float64
low       1000 non-null float64
high      1000 non-null float64
volume    1000 non-null float64
dtypes: float64(5)
memory usage: 39.1 KB

In [11]:
df['volume'] = df['volume']/1000000

In [12]:
df.head()

         open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = df.drop("volume", axis=1)
y = df["volume"]
test_size = 0.30 # taking 70:30 training and test set
seed = 7  # Random numbmer seeding for reapeatability of the code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

In [15]:
y_test.sample(n=300)

186     1.5045
113     0.4048
935     6.0706
259     2.1027
709     2.8247
172     0.6411
750     2.5758
50      0.8093
907     6.0319
43      0.8445
846     3.4566
296     1.3012
284     7.5999
779     7.1893
810     0.5110
396     3.7810
693     8.1710
972     6.2051
473     0.2860
168     0.4873
57      0.5910
718     4.1860
148     1.8652
801     2.3527
511     3.8114
780     0.1988
326     6.7109
142     0.2755
98      0.4621
222     0.8190
        ...
466     0.7948
171     0.7283
334     0.8229
794     2.1160
351     0.4812
355     7.9060
790     5.6972
362    14.6768
988     0.3699
675     3.8972
768     8.8678
696    39.3357
482     2.7281
799     1.9360
736     0.5834
63      2.0353
802     0.0100
712    13.4727
122     1.0497
590     1.1697
782    16.9736
431     1.9084
602     1.2330
297     2.1761
747     0.3246
134     0.4622
125     0.7614
839     1.5352
127     0.5911
621     0.8668
Name: volume, Length: 300, dtype: float64

#### Convert Training and Test Data to numpy float32 arrays

In [16]:
X_train = np.array(X_train).astype(np.float32)

In [17]:
X_test = np.array(X_test).astype(np.float32)

In [18]:
y_train = np.array(y_train).astype(np.float32)

In [19]:
y_test = np.array(y_test).astype(np.float32)

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [20]:
from sklearn.preprocessing import Normalizer

In [21]:
X_train = Normalizer().fit_transform(X_train)

In [22]:
X_train

array([[0.50021225, 0.5003598 , 0.49549326, 0.503899  ],
       [0.5023256 , 0.50103617, 0.4931476 , 0.5034255 ],
       [0.5004301 , 0.49899533, 0.4962851 , 0.5042563 ],
       ...,
       [0.5001929 , 0.49977148, 0.4976645 , 0.50236005],
       [0.50253594, 0.49852157, 0.496339  , 0.50257486],
       [0.50121456, 0.4987676 , 0.49595362, 0.5040285 ]], dtype=float32)

In [23]:
X_test=Normalizer().fit_transform(X_test)

In [24]:
X_test

array([[0.5063693 , 0.49396917, 0.4904527 , 0.50896037],
       [0.49942613, 0.50043815, 0.49706477, 0.5030525 ],
       [0.4963037 , 0.50399053, 0.49479976, 0.50482607],
       ...,
       [0.49629417, 0.50301725, 0.49192008, 0.5086063 ],
       [0.49930164, 0.5008185 , 0.49753195, 0.50233537],
       [0.49550715, 0.50393987, 0.49483255, 0.50562644]], dtype=float32)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [25]:
tf.reset_default_graph()

In [26]:
#Input features
x = tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')

#Normalize the data
x_n = tf.nn.l2_normalize(x,1)

#Actual Prices
y_ = tf.placeholder(shape=[None],dtype=tf.float32, name='y-input')

In [27]:
#W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

WARNING:tensorflow:From C:\Users\sgoud\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

2.Define a function to calculate prediction

In [28]:
y = tf.add(tf.matmul(x_n,W),b,name='output')

3.Loss (Cost) Function [Mean square error]

In [29]:
loss = tf.reduce_mean(tf.square(y-y_),name='Loss')

In [30]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [31]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [32]:
for epoch in range(training_epochs):
        #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:X_train, y_:y_train})
    
    if epoch % 1 == 0:
        print ('Training loss at every iteration: ', epoch, ' is ', train_loss)

Training loss at every iteration:  0  is  305.42902
Training loss at every iteration:  1  is  298.32843
Training loss at every iteration:  2  is  292.82974
Training loss at every iteration:  3  is  288.57153
Training loss at every iteration:  4  is  285.2738
Training loss at every iteration:  5  is  282.72012
Training loss at every iteration:  6  is  280.74277
Training loss at every iteration:  7  is  279.21103
Training loss at every iteration:  8  is  278.02518
Training loss at every iteration:  9  is  277.10678
Training loss at every iteration:  10  is  276.39557
Training loss at every iteration:  11  is  275.8448
Training loss at every iteration:  12  is  275.41818
Training loss at every iteration:  13  is  275.08798
Training loss at every iteration:  14  is  274.8322
Training loss at every iteration:  15  is  274.634
Training loss at every iteration:  16  is  274.4808
Training loss at every iteration:  17  is  274.3619
Training loss at every iteration:  18  is  274.2699
Training loss at every iteration:  19  is  274.1987
Training loss at every iteration:  20  is  274.14355
Training loss at every iteration:  21  is  274.10077
Training loss at every iteration:  22  is  274.06766
Training loss at every iteration:  23  is  274.0421
Training loss at every iteration:  24  is  274.02225
Training loss at every iteration:  25  is  274.0067
Training loss at every iteration:  26  is  273.99506
Training loss at every iteration:  27  is  273.9857
Training loss at every iteration:  28  is  273.97845
Training loss at every iteration:  29  is  273.973
Training loss at every iteration:  30  is  273.96872
Training loss at every iteration:  31  is  273.9656
Training loss at every iteration:  32  is  273.96283
Training loss at every iteration:  33  is  273.96088
Training loss at every iteration:  34  is  273.9594
Training loss at every iteration:  35  is  273.95813
Training loss at every iteration:  36  is  273.9572
Training loss at every iteration:  37  is  273.95645
Training loss at every iteration:  38  is  273.95602
Training loss at every iteration:  39  is  273.95563
Training loss at every iteration:  40  is  273.95538
Training loss at every iteration:  41  is  273.9548
Training loss at every iteration:  42  is  273.9548
Training loss at every iteration:  43  is  273.9546
Training loss at every iteration:  44  is  273.95447
Training loss at every iteration:  45  is  273.95447
Training loss at every iteration:  46  is  273.9544
Training loss at every iteration:  47  is  273.95428
Training loss at every iteration:  48  is  273.95425
Training loss at every iteration:  49  is  273.9543
Training loss at every iteration:  50  is  273.95425
Training loss at every iteration:  51  is  273.9541
Training loss at every iteration:  52  is  273.95416
Training loss at every iteration:  53  is  273.9541
Training loss at every iteration:  54  is  273.95422
Training loss at every iteration:  55  is  273.95407
Training loss at every iteration:  56  is  273.95416
Training loss at every iteration:  57  is  273.95422
Training loss at every iteration:  58  is  273.95416
Training loss at every iteration:  59  is  273.9541
Training loss at every iteration:  60  is  273.9541
Training loss at every iteration:  61  is  273.95413
Training loss at every iteration:  62  is  273.954
Training loss at every iteration:  63  is  273.9541
Training loss at every iteration:  64  is  273.95407
Training loss at every iteration:  65  is  273.95413
Training loss at every iteration:  66  is  273.95416
Training loss at every iteration:  67  is  273.95416
Training loss at every iteration:  68  is  273.95416
Training loss at every iteration:  69  is  273.95416
Training loss at every iteration:  70  is  273.95416
Training loss at every iteration:  71  is  273.95416
Training loss at every iteration:  72  is  273.95416
Training loss at every iteration:  73  is  273.95416
Training loss at every iteration:  74  is  273.95413
Training loss at every iteration:  75  is  273.9542
Training loss at every iteration:  76  is  273.95422
Training loss at every iteration:  77  is  273.9542
Training loss at every iteration:  78  is  273.9542
Training loss at every iteration:  79  is  273.95422
Training loss at every iteration:  80  is  273.95425
Training loss at every iteration:  81  is  273.95428
Training loss at every iteration:  82  is  273.95428
Training loss at every iteration:  83  is  273.95428
Training loss at every iteration:  84  is  273.95428
Training loss at every iteration:  85  is  273.95428
Training loss at every iteration:  86  is  273.95428
Training loss at every iteration:  87  is  273.95428
Training loss at every iteration:  88  is  273.95428
Training loss at every iteration:  89  is  273.95428
Training loss at every iteration:  90  is  273.95425
Training loss at every iteration:  91  is  273.95425
Training loss at every iteration:  92  is  273.95425
Training loss at every iteration:  93  is  273.95422
Training loss at every iteration:  94  is  273.95422
Training loss at every iteration:  95  is  273.95422
Training loss at every iteration:  96  is  273.95422
Training loss at every iteration:  97  is  273.95422
Training loss at every iteration:  98  is  273.95422
Training loss at every iteration:  99  is  273.95422

In [33]:
sess.close()

In [34]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

In [35]:
for epoch in range(training_epochs):
        #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:X_train, y_:y_train})
    
    if epoch % 5 == 0:
        print ('Training loss at every iteration: ', epoch, ' is ', train_loss)
        #numpy_array = W.eval(session=sess)

Training loss at every iteration:  0  is  305.42902
Training loss at every iteration:  5  is  282.72012
Training loss at every iteration:  10  is  276.39557
Training loss at every iteration:  15  is  274.634
Training loss at every iteration:  20  is  274.14355
Training loss at every iteration:  25  is  274.0067
Training loss at every iteration:  30  is  273.96872
Training loss at every iteration:  35  is  273.95813
Training loss at every iteration:  40  is  273.95538
Training loss at every iteration:  45  is  273.95447
Training loss at every iteration:  50  is  273.95425
Training loss at every iteration:  55  is  273.95407
Training loss at every iteration:  60  is  273.9541
Training loss at every iteration:  65  is  273.95413
Training loss at every iteration:  70  is  273.95416
Training loss at every iteration:  75  is  273.9542
Training loss at every iteration:  80  is  273.95425
Training loss at every iteration:  85  is  273.95428
Training loss at every iteration:  90  is  273.95425
Training loss at every iteration:  95  is  273.95422

In [36]:
Weight_array = W.eval(session=sess)
bias_array = b.eval(session=sess)

In [37]:
sess.close()

### Get the shapes and values of W and b

In [38]:
print('Shape of W =',W)
print('Shape of b =',b)
print('Weights Values =',Weight_array)
print('Bias Value =',bias_array)

Shape of W = <tf.Variable 'Weights:0' shape=(4, 1) dtype=float32_ref>
Shape of b = <tf.Variable 'Bias:0' shape=(1,) dtype=float32_ref>
Weights Values = [[1.4007461]
 [1.4055865]
 [1.3863369]
 [1.4173869]]
Bias Value = [2.8051822]

### Model Prediction on 1st Examples in Test Dataset

In [39]:
ypred = tf.add(tf.matmul(X_test,Weight_array),bias_array,name='output')

In [40]:
#Lets start graph Execution
sess1 = tf.Session()
ypred.eval(session=sess1)

array([[5.61012  ],
       [5.61028  ],
       [5.6102734],
       [5.6102104],
       [5.610093 ],
       [5.610279 ],
       [5.610261 ],
       [5.6102896],
       [5.6102657],
       [5.610283 ],
       [5.6102867],
       [5.6102858],
       [5.6102962],
       [5.6102734],
       [5.610194 ],
       [5.6102886],
       [5.610196 ],
       [5.610256 ],
       [5.609956 ],
       [5.6102614],
       [5.610283 ],
       [5.6102786],
       [5.610194 ],
       [5.61026  ],
       [5.610219 ],
       [5.61022  ],
       [5.6099815],
       [5.6102676],
       [5.6098657],
       [5.609933 ],
       [5.610265 ],
       [5.610116 ],
       [5.6102824],
       [5.6102037],
       [5.6102133],
       [5.6102877],
       [5.610281 ],
       [5.6102667],
       [5.610269 ],
       [5.6102657],
       [5.610289 ],
       [5.61026  ],
       [5.6102734],
       [5.610262 ],
       [5.610238 ],
       [5.610199 ],
       [5.6102457],
       [5.6102514],
       [5.610199 ],
       [5.610281 ],
       [5.6097965],
       [5.6102624],
       [5.610284 ],
       [5.6102953],
       [5.610285 ],
       [5.6102858],
       [5.61021  ],
       [5.6102495],
       [5.6101   ],
       [5.6102695],
       [5.610284 ],
       [5.610053 ],
       [5.6102667],
       [5.610261 ],
       [5.6102843],
       [5.610269 ],
       [5.6102724],
       [5.6102533],
       [5.61028  ],
       [5.6102886],
       [5.6102853],
       [5.6102467],
       [5.610283 ],
       [5.6101356],
       [5.610278 ],
       [5.610286 ],
       [5.610279 ],
       [5.610265 ],
       [5.6102858],
       [5.6102915],
       [5.610274 ],
       [5.610241 ],
       [5.6095552],
       [5.6102476],
       [5.6102033],
       [5.610257 ],
       [5.6102633],
       [5.610263 ],
       [5.610259 ],
       [5.6102505],
       [5.610263 ],
       [5.61018  ],
       [5.6101537],
       [5.6102896],
       [5.6102014],
       [5.6102786],
       [5.610139 ],
       [5.610275 ],
       [5.610278 ],
       [5.6096306],
       [5.6102824],
       [5.6102676],
       [5.610268 ],
       [5.6101933],
       [5.6102433],
       [5.6102734],
       [5.61027  ],
       [5.61028  ],
       [5.6102676],
       [5.6102805],
       [5.6102695],
       [5.6102676],
       [5.6101627],
       [5.6102448],
       [5.610257 ],
       [5.610263 ],
       [5.6102734],
       [5.610055 ],
       [5.610284 ],
       [5.610133 ],
       [5.610281 ],
       [5.6102805],
       [5.6102476],
       [5.6102066],
       [5.610284 ],
       [5.6101804],
       [5.610176 ],
       [5.6099157],
       [5.610136 ],
       [5.610279 ],
       [5.610179 ],
       [5.6102705],
       [5.6102905],
       [5.610279 ],
       [5.6102867],
       [5.610222 ],
       [5.6102448],
       [5.6102524],
       [5.6102176],
       [5.609844 ],
       [5.6102543],
       [5.610257 ],
       [5.610281 ],
       [5.610279 ],
       [5.610254 ],
       [5.610241 ],
       [5.610278 ],
       [5.6102915],
       [5.610287 ],
       [5.6102657],
       [5.6101837],
       [5.6102676],
       [5.610244 ],
       [5.610277 ],
       [5.6102595],
       [5.61029  ],
       [5.6102715],
       [5.610256 ],
       [5.610238 ],
       [5.610253 ],
       [5.610262 ],
       [5.610259 ],
       [5.6102867],
       [5.6102667],
       [5.610282 ],
       [5.610282 ],
       [5.610261 ],
       [5.6102934],
       [5.6102858],
       [5.6102953],
       [5.610253 ],
       [5.6102886],
       [5.6102858],
       [5.6102924],
       [5.6102877],
       [5.6102867],
       [5.610283 ],
       [5.610293 ],
       [5.6102076],
       [5.6102552],
       [5.6102734],
       [5.61028  ],
       [5.6102695],
       [5.6102886],
       [5.610265 ],
       [5.610295 ],
       [5.610202 ],
       [5.6102867],
       [5.6102343],
       [5.6102595],
       [5.6102896],
       [5.61028  ],
       [5.6102877],
       [5.6102633],
       [5.6102743],
       [5.6102858],
       [5.610294 ],
       [5.610159 ],
       [5.6102657],
       [5.610276 ],
       [5.6102962],
       [5.610283 ],
       [5.6102905],
       [5.610219 ],
       [5.610287 ],
       [5.61016  ],
       [5.61022  ],
       [5.610276 ],
       [5.610278 ],
       [5.6102533],
       [5.610293 ],
       [5.610279 ],
       [5.61022  ],
       [5.610259 ],
       [5.6102557],
       [5.610263 ],
       [5.610198 ],
       [5.610279 ],
       [5.6102357],
       [5.6102734],
       [5.6101913],
       [5.6102715],
       [5.610033 ],
       [5.610276 ],
       [5.6102934],
       [5.610287 ],
       [5.6102476],
       [5.6102533],
       [5.6102676],
       [5.610244 ],
       [5.610251 ],
       [5.610281 ],
       [5.610278 ],
       [5.610259 ],
       [5.6102223],
       [5.610217 ],
       [5.610292 ],
       [5.610263 ],
       [5.61026  ],
       [5.6102924],
       [5.610261 ],
       [5.610215 ],
       [5.6102943],
       [5.6102777],
       [5.610207 ],
       [5.610265 ],
       [5.6102715],
       [5.610278 ],
       [5.6102924],
       [5.610283 ],
       [5.61028  ],
       [5.608617 ],
       [5.6102886],
       [5.6101246],
       [5.610279 ],
       [5.610222 ],
       [5.6101594],
       [5.610125 ],
       [5.6102614],
       [5.6102734],
       [5.609973 ],
       [5.610282 ],
       [5.6102104],
       [5.6101704],
       [5.610222 ],
       [5.61026  ],
       [5.610255 ],
       [5.6101546],
       [5.610285 ],
       [5.610267 ],
       [5.610284 ],
       [5.61029  ],
       [5.6102905],
       [5.6102552],
       [5.6102805],
       [5.610276 ],
       [5.6102533],
       [5.6102734],
       [5.6102448],
       [5.6102858],
       [5.610281 ],
       [5.610236 ],
       [5.610258 ],
       [5.6102514],
       [5.610263 ],
       [5.610262 ],
       [5.610276 ],
       [5.610265 ],
       [5.6101522],
       [5.6102734],
       [5.6101103],
       [5.6102877],
       [5.6064987],
       [5.610256 ],
       [5.610228 ],
       [5.6099596],
       [5.6102734],
       [5.610257 ],
       [5.6102715],
       [5.6102657]], dtype=float32)

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [41]:
iris= pd.read_csv('Iris.csv')

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [42]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [44]:
X = iris.iloc[:,1:5].values
y = iris.iloc[:,5].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

### Splitting the data into feature set and target set

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [47]:
model = Sequential()
model.add(Dense(12, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

### Model Training

In [48]:
model.fit(X_train, y_train, epochs=100)

WARNING:tensorflow:From C:\Users\sgoud\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/100
120/120 [==============================] - 0s 2ms/step - loss: 2.1491 - acc: 0.3083
Epoch 2/100
120/120 [==============================] - 0s 58us/step - loss: 1.1245 - acc: 0.3667
Epoch 3/100
120/120 [==============================] - 0s 50us/step - loss: 0.9297 - acc: 0.5750
Epoch 4/100
120/120 [==============================] - 0s 84us/step - loss: 0.9050 - acc: 0.4083
Epoch 5/100
120/120 [==============================] - 0s 50us/step - loss: 0.8834 - acc: 0.3917
Epoch 6/100
120/120 [==============================] - 0s 42us/step - loss: 0.8767 - acc: 0.3833
Epoch 7/100
120/120 [==============================] - 0s 54us/step - loss: 0.8678 - acc: 0.3833
Epoch 8/100
120/120 [==============================] - 0s 72us/step - loss: 0.8476 - acc: 0.4000
Epoch 9/100
120/120 [==============================] - 0s 50us/step - loss: 0.8362 - acc: 0.3917
Epoch 10/100
120/120 [==============================] - 0s 50us/step - loss: 0.8234 - acc: 0.3917
Epoch 11/100
120/120 [==============================] - 0s 58us/step - loss: 0.8133 - acc: 0.4000
Epoch 12/100
120/120 [==============================] - 0s 59us/step - loss: 0.7955 - acc: 0.3917
Epoch 13/100
120/120 [==============================] - 0s 58us/step - loss: 0.7840 - acc: 0.4083
Epoch 14/100
120/120 [==============================] - 0s 42us/step - loss: 0.7735 - acc: 0.4250
Epoch 15/100
120/120 [==============================] - 0s 59us/step - loss: 0.7616 - acc: 0.4667
Epoch 16/100
120/120 [==============================] - 0s 59us/step - loss: 0.7504 - acc: 0.7083
Epoch 17/100
120/120 [==============================] - 0s 67us/step - loss: 0.7407 - acc: 0.6750
Epoch 18/100
120/120 [==============================] - 0s 42us/step - loss: 0.7298 - acc: 0.7250
Epoch 19/100
120/120 [==============================] - 0s 54us/step - loss: 0.7166 - acc: 0.7500
Epoch 20/100
120/120 [==============================] - 0s 54us/step - loss: 0.7048 - acc: 0.7333
Epoch 21/100
120/120 [==============================] - 0s 54us/step - loss: 0.6959 - acc: 0.7250
Epoch 22/100
120/120 [==============================] - 0s 50us/step - loss: 0.6821 - acc: 0.7333
Epoch 23/100
120/120 [==============================] - 0s 58us/step - loss: 0.6717 - acc: 0.7417
Epoch 24/100
120/120 [==============================] - 0s 42us/step - loss: 0.6610 - acc: 0.7500
Epoch 25/100
120/120 [==============================] - 0s 59us/step - loss: 0.6501 - acc: 0.7167
Epoch 26/100
120/120 [==============================] - 0s 50us/step - loss: 0.6426 - acc: 0.7250
Epoch 27/100
120/120 [==============================] - 0s 42us/step - loss: 0.6315 - acc: 0.7250
Epoch 28/100
120/120 [==============================] - 0s 59us/step - loss: 0.6230 - acc: 0.7333
Epoch 29/100
120/120 [==============================] - 0s 67us/step - loss: 0.6196 - acc: 0.7333
Epoch 30/100
120/120 [==============================] - 0s 58us/step - loss: 0.6077 - acc: 0.7417
Epoch 31/100
120/120 [==============================] - 0s 58us/step - loss: 0.5958 - acc: 0.7500
Epoch 32/100
120/120 [==============================] - 0s 59us/step - loss: 0.5889 - acc: 0.7333
Epoch 33/100
120/120 [==============================] - 0s 42us/step - loss: 0.5805 - acc: 0.7833
Epoch 34/100
120/120 [==============================] - 0s 75us/step - loss: 0.5776 - acc: 0.7917
Epoch 35/100
120/120 [==============================] - 0s 50us/step - loss: 0.5690 - acc: 0.7833
Epoch 36/100
120/120 [==============================] - 0s 58us/step - loss: 0.5617 - acc: 0.8167
Epoch 37/100
120/120 [==============================] - 0s 67us/step - loss: 0.5539 - acc: 0.7500
Epoch 38/100
120/120 [==============================] - 0s 59us/step - loss: 0.5470 - acc: 0.7750
Epoch 39/100
120/120 [==============================] - 0s 50us/step - loss: 0.5444 - acc: 0.8250
Epoch 40/100
120/120 [==============================] - 0s 75us/step - loss: 0.5439 - acc: 0.8667
Epoch 41/100
120/120 [==============================] - 0s 50us/step - loss: 0.5325 - acc: 0.7667
Epoch 42/100
120/120 [==============================] - 0s 50us/step - loss: 0.5233 - acc: 0.7667
Epoch 43/100
120/120 [==============================] - 0s 42us/step - loss: 0.5178 - acc: 0.8250
Epoch 44/100
120/120 [==============================] - 0s 59us/step - loss: 0.5140 - acc: 0.8417
Epoch 45/100
120/120 [==============================] - 0s 67us/step - loss: 0.5080 - acc: 0.8250
Epoch 46/100
120/120 [==============================] - 0s 54us/step - loss: 0.5060 - acc: 0.8500
Epoch 47/100
120/120 [==============================] - 0s 50us/step - loss: 0.4977 - acc: 0.8333
Epoch 48/100
120/120 [==============================] - 0s 50us/step - loss: 0.4950 - acc: 0.8500
Epoch 49/100
120/120 [==============================] - 0s 58us/step - loss: 0.4922 - acc: 0.8333
Epoch 50/100
120/120 [==============================] - 0s 58us/step - loss: 0.4854 - acc: 0.8667
Epoch 51/100
120/120 [==============================] - 0s 50us/step - loss: 0.4809 - acc: 0.8667
Epoch 52/100
120/120 [==============================] - 0s 50us/step - loss: 0.4781 - acc: 0.8667
Epoch 53/100
120/120 [==============================] - 0s 75us/step - loss: 0.4767 - acc: 0.7667
Epoch 54/100
120/120 [==============================] - 0s 58us/step - loss: 0.4764 - acc: 0.8333
Epoch 55/100
120/120 [==============================] - 0s 42us/step - loss: 0.4650 - acc: 0.8583
Epoch 56/100
120/120 [==============================] - 0s 42us/step - loss: 0.4622 - acc: 0.9083
Epoch 57/100
120/120 [==============================] - 0s 63us/step - loss: 0.4594 - acc: 0.8583
Epoch 58/100
120/120 [==============================] - 0s 48us/step - loss: 0.4559 - acc: 0.8333
Epoch 59/100
120/120 [==============================] - 0s 42us/step - loss: 0.4536 - acc: 0.8833
Epoch 60/100
120/120 [==============================] - 0s 42us/step - loss: 0.4503 - acc: 0.8750
Epoch 61/100
120/120 [==============================] - 0s 58us/step - loss: 0.4469 - acc: 0.8750
Epoch 62/100
120/120 [==============================] - 0s 58us/step - loss: 0.4440 - acc: 0.8417
Epoch 63/100
120/120 [==============================] - 0s 58us/step - loss: 0.4430 - acc: 0.8750
Epoch 64/100
120/120 [==============================] - 0s 33us/step - loss: 0.4393 - acc: 0.8167
Epoch 65/100
120/120 [==============================] - 0s 50us/step - loss: 0.4371 - acc: 0.9333
Epoch 66/100
120/120 [==============================] - 0s 42us/step - loss: 0.4310 - acc: 0.8667
Epoch 67/100
120/120 [==============================] - 0s 50us/step - loss: 0.4291 - acc: 0.9000
Epoch 68/100
120/120 [==============================] - 0s 58us/step - loss: 0.4261 - acc: 0.8833
Epoch 69/100
120/120 [==============================] - 0s 33us/step - loss: 0.4242 - acc: 0.9000
Epoch 70/100
120/120 [==============================] - 0s 67us/step - loss: 0.4253 - acc: 0.9000
Epoch 71/100
120/120 [==============================] - 0s 58us/step - loss: 0.4183 - acc: 0.9000
Epoch 72/100
120/120 [==============================] - 0s 46us/step - loss: 0.4167 - acc: 0.8667
Epoch 73/100
120/120 [==============================] - 0s 42us/step - loss: 0.4187 - acc: 0.9000
Epoch 74/100
120/120 [==============================] - 0s 58us/step - loss: 0.4172 - acc: 0.8583
Epoch 75/100
120/120 [==============================] - 0s 42us/step - loss: 0.4092 - acc: 0.9250
Epoch 76/100
120/120 [==============================] - 0s 42us/step - loss: 0.4095 - acc: 0.9000
Epoch 77/100
120/120 [==============================] - 0s 75us/step - loss: 0.4034 - acc: 0.8833
Epoch 78/100
120/120 [==============================] - 0s 42us/step - loss: 0.4020 - acc: 0.8667
Epoch 79/100
120/120 [==============================] - 0s 58us/step - loss: 0.4020 - acc: 0.9500
Epoch 80/100
120/120 [==============================] - 0s 50us/step - loss: 0.3966 - acc: 0.8917
Epoch 81/100

120/120 [==============================] - 0s 67us/step - loss: 0.3949 - acc: 0.9250
Epoch 82/100
120/120 [==============================] - 0s 50us/step - loss: 0.3929 - acc: 0.9000
Epoch 83/100
120/120 [==============================] - 0s 50us/step - loss: 0.3929 - acc: 0.9167
Epoch 84/100
120/120 [==============================] - 0s 50us/step - loss: 0.3890 - acc: 0.8917
Epoch 85/100
120/120 [==============================] - 0s 67us/step - loss: 0.3873 - acc: 0.9500
Epoch 86/100
120/120 [==============================] - 0s 50us/step - loss: 0.3849 - acc: 0.9167
Epoch 87/100
120/120 [==============================] - 0s 42us/step - loss: 0.3855 - acc: 0.9167
Epoch 88/100
120/120 [==============================] - 0s 58us/step - loss: 0.3800 - acc: 0.9417
Epoch 89/100
120/120 [==============================] - 0s 58us/step - loss: 0.3814 - acc: 0.9167
Epoch 90/100
120/120 [==============================] - 0s 67us/step - loss: 0.3768 - acc: 0.8917
Epoch 91/100
120/120 [==============================] - 0s 75us/step - loss: 0.3780 - acc: 0.9417
Epoch 92/100
120/120 [==============================] - 0s 50us/step - loss: 0.3743 - acc: 0.9333
Epoch 93/100
120/120 [==============================] - 0s 59us/step - loss: 0.3706 - acc: 0.9167
Epoch 94/100
120/120 [==============================] - 0s 42us/step - loss: 0.3689 - acc: 0.9333
Epoch 95/100
120/120 [==============================] - 0s 75us/step - loss: 0.3677 - acc: 0.9167
Epoch 96/100
120/120 [==============================] - 0s 50us/step - loss: 0.3682 - acc: 0.9250
Epoch 97/100
120/120 [==============================] - 0s 65us/step - loss: 0.3649 - acc: 0.9167
Epoch 98/100
120/120 [==============================] - 0s 42us/step - loss: 0.3612 - acc: 0.9333
Epoch 99/100
120/120 [==============================] - 0s 58us/step - loss: 0.3621 - acc: 0.9167
Epoch 100/100
120/120 [==============================] - 0s 42us/step - loss: 0.3588 - acc: 0.9417

### Model Prediction

In [49]:
y_predict = model.predict(X)
y_predict

array([[9.21900809e-01, 7.65752494e-02, 1.52386376e-03],
       [9.00922298e-01, 9.63693857e-02, 2.70838127e-03],
       [9.06772852e-01, 9.07676071e-02, 2.45958520e-03],
       [8.77057731e-01, 1.18790761e-01, 4.15149564e-03],
       [9.21721816e-01, 7.67310932e-02, 1.54712377e-03],
       [9.20262814e-01, 7.84148052e-02, 1.32239715e-03],
       [9.02094007e-01, 9.53031704e-02, 2.60282541e-03],
       [9.12793994e-01, 8.52967054e-02, 1.90925074e-03],
       [8.68605971e-01, 1.26252130e-01, 5.14184078e-03],
       [8.98336351e-01, 9.89218429e-02, 2.74177315e-03],
       [9.31250215e-01, 6.76691905e-02, 1.08065293e-03],
       [8.91271293e-01, 1.05777435e-01, 2.95129488e-03],
       [9.01874304e-01, 9.54244807e-02, 2.70122173e-03],
       [8.90978754e-01, 1.05304249e-01, 3.71689792e-03],
       [9.42410946e-01, 5.69427647e-02, 6.46271859e-04],
       [9.46843028e-01, 5.26051745e-02, 5.51777892e-04],
       [9.34973955e-01, 6.40953779e-02, 9.30647715e-04],
       [9.22214806e-01, 7.62698203e-02, 1.51534262e-03],
       [9.30466533e-01, 6.85480908e-02, 9.85418214e-04],
       [9.24634635e-01, 7.40229189e-02, 1.34246179e-03],
       [9.04948533e-01, 9.30254385e-02, 2.02599308e-03],
       [9.21357214e-01, 7.71802962e-02, 1.46250671e-03],
       [9.12941337e-01, 8.50250348e-02, 2.03360990e-03],
       [8.64639342e-01, 1.31063446e-01, 4.29724669e-03],
       [8.37778389e-01, 1.56146422e-01, 6.07516104e-03],
       [8.75538588e-01, 1.20480321e-01, 3.98111204e-03],
       [8.89177084e-01, 1.07856661e-01, 2.96624075e-03],
       [9.22342658e-01, 7.61939362e-02, 1.46332558e-03],
       [9.22079265e-01, 7.64197260e-02, 1.50095392e-03],
       [8.72765720e-01, 1.23024479e-01, 4.20970609e-03],
       [8.71327519e-01, 1.24363825e-01, 4.30868426e-03],
       [9.19593990e-01, 7.88772106e-02, 1.52884342e-03],
       [9.33925152e-01, 6.50839135e-02, 9.90935485e-04],
       [9.40646648e-01, 5.86227328e-02, 7.30567321e-04],
       [8.98336351e-01, 9.89218429e-02, 2.74177315e-03],
       [9.13793802e-01, 8.42621848e-02, 1.94398419e-03],
       [9.29681361e-01, 6.92042783e-02, 1.11433677e-03],
       [8.98336351e-01, 9.89218429e-02, 2.74177315e-03],
       [8.89897585e-01, 1.06427439e-01, 3.67501169e-03],
       [9.16499317e-01, 8.17714483e-02, 1.72923785e-03],
       [9.20116067e-01, 7.82612115e-02, 1.62273110e-03],
       [8.38191926e-01, 1.53255597e-01, 8.55250470e-03],
       [8.96015644e-01, 1.00768983e-01, 3.21531040e-03],
       [8.83201420e-01, 1.13570675e-01, 3.22796009e-03],
       [8.72857630e-01, 1.23791777e-01, 3.35065252e-03],
       [8.90446782e-01, 1.06213361e-01, 3.33984080e-03],
       [9.20137763e-01, 7.83995017e-02, 1.46269263e-03],
       [8.97683561e-01, 9.93916690e-02, 2.92479852e-03],
       [9.29412425e-01, 6.94209784e-02, 1.16651156e-03],
       [9.15883362e-01, 8.22589695e-02, 1.85762777e-03],
       [6.26658946e-02, 6.22755229e-01, 3.14578801e-01],
       [5.59323616e-02, 5.86196601e-01, 3.57871085e-01],
       [3.44893374e-02, 5.49136698e-01, 4.16373909e-01],
       [3.98209579e-02, 4.71781850e-01, 4.88397270e-01],
       [3.50201502e-02, 5.19501150e-01, 4.45478737e-01],
       [2.74476372e-02, 4.59942132e-01, 5.12610197e-01],
       [3.61982509e-02, 5.37473857e-01, 4.26327944e-01],
       [1.29556820e-01, 5.64494014e-01, 3.05949181e-01],
       [4.81865481e-02, 5.67722857e-01, 3.84090662e-01],
       [5.15884571e-02, 5.05712807e-01, 4.42698747e-01],
       [7.00996518e-02, 5.02508521e-01, 4.27391797e-01],
       [5.80735989e-02, 5.60032129e-01, 3.81894290e-01],
       [6.64699078e-02, 5.47550201e-01, 3.85979831e-01],
       [2.52943002e-02, 4.69954520e-01, 5.04751146e-01],
       [1.42705232e-01, 6.09761000e-01, 2.47533843e-01],
       [8.04708898e-02, 6.27317905e-01, 2.92211205e-01],
       [2.59725321e-02, 4.55660403e-01, 5.18367052e-01],
       [7.36925676e-02, 5.72262168e-01, 3.54045242e-01],
       [1.89905427e-02, 4.06066835e-01, 5.74942589e-01],
       [7.25161135e-02, 5.52021801e-01, 3.75462115e-01],
       [1.66665390e-02, 4.19552207e-01, 5.63781202e-01],
       [9.29003283e-02, 6.03048444e-01, 3.04051220e-01],
       [1.19597074e-02, 3.69590163e-01, 6.18450105e-01],
       [2.72182152e-02, 4.77029711e-01, 4.95752066e-01],
       [7.24659786e-02, 5.99662185e-01, 3.27871889e-01],
       [6.97631538e-02, 6.07401133e-01, 3.22835743e-01],
       [3.21270265e-02, 5.23501277e-01, 4.44371700e-01],
       [1.87380444e-02, 4.58573222e-01, 5.22688746e-01],
       [3.21558900e-02, 4.93098587e-01, 4.74745512e-01],
       [1.72611564e-01, 6.07019305e-01, 2.20369160e-01],
       [7.46518746e-02, 5.46038210e-01, 3.79309952e-01],
       [9.59402695e-02, 5.68610072e-01, 3.35449666e-01],
       [9.05197933e-02, 5.86533010e-01, 3.22947234e-01],
       [6.66987570e-03, 3.02885681e-01, 6.90444410e-01],
       [2.21433397e-02, 4.28500712e-01, 5.49355924e-01],
       [4.66424897e-02, 5.58385849e-01, 3.94971669e-01],
       [4.36728559e-02, 5.67687094e-01, 3.88639957e-01],
       [3.30916792e-02, 4.83482897e-01, 4.83425438e-01],
       [6.60958141e-02, 5.63486516e-01, 3.70417684e-01],
       [4.79295775e-02, 5.02126813e-01, 4.49943572e-01],
       [2.57677864e-02, 4.36423689e-01, 5.37808537e-01],
       [3.39273065e-02, 5.09956479e-01, 4.56116259e-01],
       [6.99056610e-02, 5.59900522e-01, 3.70193750e-01],
       [1.27667487e-01, 5.63246548e-01, 3.09085935e-01],
       [4.20425273e-02, 5.01034796e-01, 4.56922680e-01],
       [6.36150092e-02, 5.65313995e-01, 3.71071011e-01],
       [5.40687703e-02, 5.42519033e-01, 4.03412253e-01],
       [6.34851605e-02, 5.79463840e-01, 3.57050955e-01],
       [2.29319528e-01, 5.75913846e-01, 1.94766611e-01],
       [5.97117580e-02, 5.48148572e-01, 3.92139643e-01],
       [8.70253192e-04, 1.56672642e-01, 8.42457056e-01],
       [4.14456241e-03, 2.48489335e-01, 7.47366130e-01],
       [2.51675956e-03, 2.49193564e-01, 7.48289704e-01],
       [2.87102372e-03, 2.38046929e-01, 7.59082019e-01],
       [1.62735826e-03, 1.97520703e-01, 8.00851941e-01],
       [7.70442595e-04, 1.71143591e-01, 8.28085899e-01],
       [6.97661564e-03, 2.64493257e-01, 7.28530169e-01],
       [1.42575556e-03, 2.07559213e-01, 7.91014969e-01],
       [1.63586996e-03, 1.92633003e-01, 8.05731177e-01],
       [2.33007176e-03, 2.60801226e-01, 7.36868739e-01],
       [1.21199694e-02, 4.02507633e-01, 5.85372388e-01],
       [4.55199275e-03, 2.74767429e-01, 7.20680594e-01],
       [4.79081972e-03, 3.01035464e-01, 6.94173753e-01],
       [3.41999158e-03, 2.22460926e-01, 7.74119079e-01],
       [2.82534864e-03, 2.14948684e-01, 7.82225907e-01],
       [5.41525893e-03, 3.05456132e-01, 6.89128578e-01],
       [4.87545179e-03, 2.96489537e-01, 6.98635042e-01],
       [1.55903387e-03, 2.48813972e-01, 7.49626994e-01],
       [2.00296912e-04, 9.59224403e-02, 9.03877258e-01],
       [5.26252761e-03, 2.63351709e-01, 7.31385708e-01],
       [3.42876441e-03, 2.76294529e-01, 7.20276654e-01],
       [5.55540808e-03, 2.71497488e-01, 7.22947061e-01],
       [5.79900749e-04, 1.51849791e-01, 8.47570240e-01],
       [1.12138325e-02, 3.66792202e-01, 6.21993959e-01],
       [3.88247101e-03, 2.87844121e-01, 7.08273470e-01],
       [3.68867605e-03, 2.98613220e-01, 6.97698116e-01],
       [1.41936755e-02, 3.94459277e-01, 5.91347039e-01],
       [1.29584381e-02, 3.88750762e-01, 5.98290801e-01],
       [2.07750476e-03, 2.08772540e-01, 7.89149940e-01],
       [5.61407115e-03, 3.37442040e-01, 6.56943858e-01],
       [2.02313066e-03, 2.34362796e-01, 7.63614058e-01],
       [4.46875533e-03, 3.65213931e-01, 6.30317271e-01],
       [1.87695504e-03, 2.00269118e-01, 7.97853887e-01],
       [1.06255952e-02, 3.68895501e-01, 6.20478928e-01],
       [2.49684928e-03, 2.16080099e-01, 7.81423092e-01],
       [2.27127038e-03, 2.55244434e-01, 7.42484272e-01],
       [2.82104756e-03, 2.46410698e-01, 7.50768185e-01],
       [4.97927377e-03, 2.99048454e-01, 6.95972264e-01],
       [1.47610707e-02, 4.00117218e-01, 5.85121691e-01],
       [7.30148284e-03, 3.53409797e-01, 6.39288664e-01],
       [2.90236925e-03, 2.50592470e-01, 7.46505201e-01],
       [1.16530573e-02, 4.04897332e-01, 5.83449602e-01],
       [4.14456241e-03, 2.48489335e-01, 7.47366130e-01],
       [1.95961073e-03, 2.24065796e-01, 7.73974538e-01],
       [2.62252078e-03, 2.47105703e-01, 7.50271797e-01],
       [7.10458728e-03, 3.36569935e-01, 6.56325459e-01],
       [6.58064894e-03, 3.00416112e-01, 6.93003237e-01],
       [7.89901800e-03, 3.44830126e-01, 6.47270858e-01],
       [4.50086780e-03, 2.87824571e-01, 7.07674503e-01],
       [7.01802410e-03, 3.13758016e-01, 6.79224014e-01]], dtype=float32)

### Save the Model

In [50]:
import pickle
# Save the trained model as a pickle file. 
pickle.dump(model, open("model.pkl","wb"))